#!/usr/bin/python
import RPi.GPIO as GPIO
import os.path as path
import signal
import json
from sys import exit
from time import sleep
from thread import start_new_thread

a=32
b=33
c=36
d=35
e=38
f=37
g=40

da=18
db=19
dc=22
dd=21

ia=26
ib=31

def readJSON(f):
	s="/var/www/html/tmp/"+f
	while not path.isfile(s):
		sleep(1)
	try:
		with open(s,'r') as cfg:
			s=json.load(cfg)
	except:
		print "The file "+f+" is not readable"
		sleep(0.005)
		s=readJSON(f)
	return s
def toInt(i):
	return int(round(i,0))
def strInt(i):
	if i == "-":
		return 10
	elif i == "":
		return 11
	elif i == "A":
		return 12
	elif i == "C":
		return 13
	elif i == "E":
		return 14
	elif i == "F":
		return 15
	elif i == "J":
		return 16
	elif i == "L":
		return 17
	elif i == "P":
		return 18
	elif i == "U":
		return 19
	return int(float(i))
def saveTarget(adj):
	with open("/var/www/html/config.json",'r+') as f:
		cfg=json.load(f)
		cfg["enabled"]=1
		cfg["target"]=cfg["target"]+adj
		f.seek(0)
		json.dump(cfg, f)
		f.truncate()
	return cfg
def showTarget(on):
	target=str(on)
	numbers[2]=strInt(target[-2:-1])
	numbers[3]=strInt(target[-1:])
def LCD_panel():
	then=3
	now=0
	while RUN:
		then=now
		now=then+1
		if now>3:
			now=0
		GPIO.output(digits[then], 1)
		ct=0
		for i in segments[numbers[now]]:
			GPIO.output(panel[ct], i)
			ct=ct+1
		GPIO.output(digits[now], 0)
		sleep(0.0055)
def terminate(*args):
	RUN=False
	sleep(0.1)
	GPIO.cleanup()
	print "\n"
	exit(0)

GPIO.setmode(GPIO.BOARD)
for i in [a,b,c,d,e,f,g,da,db,dc,dd]:
	GPIO.setup(i, GPIO.OUT)
	GPIO.output(i, 1)
for i in [ib,ia]:
        GPIO.setup(i, GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
signal.signal(signal.SIGINT, terminate)
#        A  B  C  D  E  F  G
panel=[a,b,c,d,e,f,g]
segments=[]
# 7 Segement LED layout
#   A
# F   B
#   G
# E   C
#   D
#                A B C D E F G
segments.append([0,0,0,0,0,0,1])# 0
segments.append([1,0,0,1,1,1,1])# 1
segments.append([0,0,1,0,0,1,0])# 2
segments.append([0,0,0,0,1,1,0])# 3
segments.append([1,0,0,1,1,0,0])# 4
segments.append([0,1,0,0,1,0,0])# 5
segments.append([1,1,0,0,0,0,0])# 6
segments.append([0,0,0,1,1,1,1])# 7
segments.append([0,0,0,0,0,0,0])# 8
segments.append([0,0,0,1,1,0,0])# 9
segments.append([1,1,1,1,1,1,0])# -
segments.append([1,1,1,1,1,1,1])# blank
segments.append([0,0,0,1,0,0,0])# A
segments.append([0,1,1,0,0,0,1])# C
segments.append([0,1,1,0,0,0,0])# E
segments.append([0,1,1,1,0,0,0])# F
segments.append([1,0,0,0,0,1,1])# J
segments.append([1,1,1,0,0,0,1])# L
segments.append([0,0,1,1,0,0,0])# P
segments.append([1,0,0,0,0,0,1])# U

digits=[da,db,dc,dd]
numbers=[11,11,11,11]
RUN=True
start_new_thread(LCD_panel,())
try:
	while True:
		# {"format":"F","on":21111,"off":20278,"temp":21750,"enable":0,"relay":0}
		lcd=readJSON('lcd.json')
		temp=lcd["temp"]
		on=lcd["on"]
		off=lcd["off"]
		cp=lcd["off"]==on
		relay=lcd["relay"]
		if(lcd["format"]=="F"):
			temp=toInt((temp*1.8+32000.0)/1000.0)
			on=toInt((on*1.8+32000.0)/1000.0)
			off=toInt((off*1.8+32000.0)/1000.0)
		else:
			temp=toInt(temp/1000.0)
			on=toInt(on/1000.0)
			off=toInt(off/1000.0)
		if(relay==(lcd["on"]>lcd["off"])):
			event=off
		else:
			event=on
		thermal=str(temp)
		numbers[0]=strInt(thermal[-2:-1])
		numbers[1]=strInt(thermal[-1:])
		if cp:
			showTarget("CP")
		elif GPIO.input(ia) or GPIO.input(ib):
			adj=0
			while GPIO.input(ia) or GPIO.input(ib):
				if lcd["enable"] == 0:
					lcd["enable"]=1
				elif GPIO.input(ia):
					event=event-1
					adj=adj-1
				else:
					event=event+1
					adj=adj+1
				showTarget(event)
				sleep(1)
			saveTarget(adj)
			sleep(2.5)
		elif lcd["enable"] == 1:
			showTarget(event)
		else:
			showTarget("")
		sleep(1.2)
except KeyboardInterrupt:
	terminate()
